### ISSUE TITLE
Build fails on Windows 10 

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/cli-blockstack#17] opened 2019-05-05 16:14 UTC
https://forum.blockstack.org/t/error-when-downloading-blockstack-cli/8002

When downloading the blockstack cli, I encounter the following error:

```
PS C:\Users\Owner\cli-blockstack> npm run build

blockstack-cli@0.0.1 build C:\Users\Owner\cli-blockstack
tsc && chmod +x lib/index.js

src/cli.ts:2414:9 - error TS2345: Argument of type ‘(tokenList: { tokens: string[]; }) => Promise<{ ‘token’: string; ‘amount’: string; }[]>’ is not assignable to parameter of type ‘(value: string[]) => { ‘token’: string; ‘amount’: string; }[] | PromiseLike<{ ‘token’: string; ‘amount’: string; }[]>’.
Types of parameters ‘tokenList’ and ‘value’ are incompatible.
Property ‘tokens’ is missing in type ‘string[]’ but required in type ‘{ tokens: string[]; }’.

2414 .then((tokenList : { tokens: string[] }) => {
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/cli.ts:2414:24
2414 .then((tokenList : { tokens: string[] }) => {
~~~~~~
‘tokens’ is declared here.

Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! blockstack-cli@0.0.1 build: tsc && chmod +x lib/index.js
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the blockstack-cli@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I’m following these instructions and am using Windows 10

**Comment by talhasch** [comment] 2019-05-05 19:59
I encountered same problem either on macOS Sierra 10.12.6 with node v8.11.2

**Comment by jcnelson** [comment] 2019-05-05 20:17
Reproduced locally.  Pushed a possible fix.  Please try again.

**Comment by talhasch** [comment] 2019-05-05 20:26
worked for me.

**Comment by davisl** [comment] 2019-05-05 21:48
Tried again but just throws this error:
PS C:\Users\Owner\cli-blockstack> npm run build

> blockstack-cli@0.0.1 build C:\Users\Owner\cli-blockstack
> tsc && chmod +x lib/index.js

'chmod' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blockstack-cli@0.0.1 build: `tsc && chmod +x lib/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blockstack-cli@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by davisl** [comment] 2019-05-05 22:05
Also I'm using node v10.15.3 and npm v6.4.1

**Comment by zone117x** [comment] 2019-05-06 13:11
@jcnelson feel free to delegate this to me

**Comment by jcnelson** [comment] 2019-05-07 15:35
@zone117x please do -- the problem is that for whatever reason, npm isn't making the resulting file executable.  As a hacky workaround, I modified the build script to `chmod` the file directly, but this isn't portable to Windows.

**Comment by zone117x** [comment] 2019-08-05 23:10
This was fixed by @jcnelson a while ago in https://github.com/blockstack/cli-blockstack/commit/81bf2c42ca26a684e2f2ba8d509889526658319b

Just tested installation on Windows 10 with latest master branch using:
```
npm install -g https://github.com/blockstack/cli-blockstack
blockstack-cli help
```
Installs and runs successfully.

Tested commands:
```
blockstack-cli gaia_listfiles "https://hub.blockstack.org" "bcf28d02ae1c306d8....."
> [Successful list files]
```

And 
```
blockstack-cli authenticator https://hub.blockstack.org "kit gym peace ..."
```
Successful sign in to a Blockstack app using the Blockstack Browser for Windows in dev mode.


@moxiegirl want to verify? Then I think we can close this ticket.

**Comment by moxiegirl** [comment] 2019-08-07 20:24
@zone117x I don't have time to spin up a test node. If you tested it and are satisifed, that's fine with me.  @timstackblock if you have a fast way to test this...feel free. Otherwise, I think we satisfied the customer who filed the original complaint on the forum.

**Comment by timstackblock** [comment] 2019-08-08 16:27
I don't have a fast way to test this but, I can run a full retest on windows if you guys want, starting now.

**Comment by timstackblock** [comment] 2019-08-09 14:34
<img width="1002" alt="Screen Shot 2019-08-09 at 10 31 32 AM" src="https://user-images.githubusercontent.com/49165468/62786575-e1ed6800-ba90-11e9-8077-9ba3161af14c.png">

I am getting the following error, I am verifying my setup now but I believe I have all dependencies installed.

```C:\Users\twell\cli-blockstack>npm install -g https://github.com/blockstack/cli-blockstack
C:\Users\twell\AppData\Roaming\npm\blockstack-cli -> C:\Users\twell\AppData\Roaming\npm\node_modules\blockstack-cli\cmd\index.js

> tiny-secp256k1@1.1.3 install C:\Users\twell\AppData\Roaming\npm\node_modules\blockstack-cli\node_modules\tiny-secp256k1
> npm run build || echo "secp256k1 bindings compilation fail. Pure JS implementation will be used."


> tiny-secp256k1@1.1.3 build C:\Users\twell\AppData\Roaming\npm\node_modules\blockstack-cli\node_modules\tiny-secp256k1
> node-gyp rebuild


C:\Users\twell\AppData\Roaming\npm\node_modules\blockstack-cli\node_modules\tiny-secp256k1>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\twell\AppData\Roaming\npm\node_modules\blockstack-cli\node_modules\tiny-secp256k1
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.1.3 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tiny-secp256k1@1.1.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\twell\AppData\Roaming\npm-cache\_logs\2019-08-09T14_22_52_372Z-debug.log
"secp256k1 bindings compilation fail. Pure JS implementation will be used."
+ blockstack-cli@1.0.0
added 256 packages from 285 contributors in 1183.097s

C:\Users\twell\cli-blockstack>```

**Comment by moxiegirl** [comment] 2019-08-09 17:38
@timstackblock This is how I tell people to build an environment on Windows for Blockstack:

https://docs.blockstack.org/develop/zero_to_dapp_2_win.html

**Comment by timstackblock** [comment] 2019-08-09 17:39
Updated python with 
```npm --add-python-to-path='true' --debug install --global windows-build-tools```

Ran the command again 
```npm install -g https://github.com/blockstack/cli-blockstack```

and it installed without error I am closing this issue.

**Closed as completed by timstackblock** 2019-08-09 17:39 UTC
